### ISSUE TITLE
Adjusting figsize of plots

### ISSUE THREAD

**Issue by charliebrookerBH** [BHoM/LadybugTools_Toolkit#98]
#### Description:

Hi team, I find the default figsizes are something that I'm regularly interested in adjusting (and the ones on the current climate dashboard don't particularly work well for A4 reports). 

I'm sure there's a way to handle this easily with Matplotlib, but for those of us less familiar with it, please could we expose figsize as a variable in the plot methods? 

E.g. this 
![image](https://github.com/BHoM/LadybugTools_Toolkit/assets/26814591/c89be98b-915b-4556-85ed-bdfdaa924160)

Welcome thoughts on if there's a better approach for this. 

Cheers,

**Comment by jamesramsden-bh** [comment]
Long story short, this is by design. Plots are now returned as axis objects, which allows more flexibility at the cost of a slightly more involved setup. 

I kept forgetting the syntax for setting it up myself too, so I added it to the wiki page: https://github.com/BHoM/LadybugTools_Toolkit/wiki/Plot-types#axes-and-figures
